import { DRY_PARAMS, type EffectParams, type PresetParams } from "./params";

export type PresetGroup =
  "Speech" | "Karaoke" | "Singing" | "Mehfil" | "Qawwali" | "Tillawat" | "Naat" | "FX";

export type Preset = {
  id: string;
  name: string;
  group: PresetGroup;
  hint: string;
  params: PresetParams;
};

export const GROUP_ORDER: PresetGroup[] = [
  "Speech",
  "Karaoke",
  "Singing",
  "Mehfil",
  "Qawwali",
  "Tillawat",
  "Naat",
  "FX",
];

export const GROUP_NOTES: Record<PresetGroup, string> = {
  Speech: "Dry and intelligible — no echo",
  Karaoke: "Light reverb, little to no echo",
  Singing: "Studio vocal spaces, graded by size",
  Mehfil: "Live gathering echo — subtle to hall",
  Qawwali: "Powerful, rhythmic repeats",
  Tillawat: "Recitation echo — slow, clean repeats",
  Naat: "Melodic warmth with gentle repeats",
  FX: "Character effects",
};

/**
 * Presets are pure data layered over DRY_PARAMS. Anything a preset does not
 * mention resolves to its dry value, so no preset can leave a stale effect on.
 */
export const PRESETS: Preset[] = [
  // ── Speech ──────────────────────────────────────────────────────────────
  {
    id: "clean",
    name: "Clean",
    group: "Speech",
    hint: "True dry signal, zero effects",
    params: { wet: 0, lowCut: 75 },
  },
  {
    id: "podcast",
    name: "Podcast",
    group: "Speech",
    hint: "Warm and tight, no echo",
    params: {
      wet: 0.25,
      lowCut: 110,
      eqLow: 2,
      eqMid: -1.5,
      eqMidFreq: 500,
      eqHigh: 2.5,
      drive: 0.06,
      reverbMix: 0.14,
      reverbSize: 0.12,
      reverbDecay: 0.25,
      reverbDamp: 0.6,
    },
  },
  {
    id: "announcer",
    name: "Announcer",
    group: "Speech",
    hint: "PA presence, no repeats",
    params: {
      wet: 0.4,
      lowCut: 130,
      eqLow: -1,
      eqMid: 3.5,
      eqMidFreq: 2600,
      eqHigh: 2,
      drive: 0.12,
      reverbMix: 0.3,
      reverbSize: 0.3,
      reverbDecay: 0.35,
      reverbDamp: 0.5,
    },
  },

  // ── Karaoke ─────────────────────────────────────────────────────────────
  {
    id: "karaoke-soft",
    name: "Karaoke Soft",
    group: "Karaoke",
    hint: "Just a touch of room",
    params: {
      wet: 0.35,
      lowCut: 100,
      eqHigh: 1.5,
      reverbMix: 0.28,
      reverbSize: 0.25,
      reverbDecay: 0.4,
      reverbDamp: 0.5,
    },
  },
  {
    id: "karaoke-std",
    name: "Karaoke Std",
    group: "Karaoke",
    hint: "Light plate reverb",
    params: {
      wet: 0.45,
      lowCut: 100,
      eqLow: 1,
      eqHigh: 2,
      reverbMix: 0.42,
      reverbSize: 0.38,
      reverbDecay: 0.5,
      reverbDamp: 0.4,
    },
  },
  {
    id: "karaoke-wide",
    name: "Karaoke Wide",
    group: "Karaoke",
    hint: "Roomy, gently widened",
    params: {
      wet: 0.55,
      lowCut: 105,
      eqHigh: 2.5,
      reverbMix: 0.55,
      reverbSize: 0.5,
      reverbDecay: 0.55,
      reverbDamp: 0.35,
      delayMix: 0.08,
      delayTime: 0.11,
      delayFeedback: 0.12,
      delayDamp: 0.5,
      chorusMix: 0.18,
      chorusRate: 0.6,
      chorusDepth: 0.3,
    },
  },
  {
    id: "party",
    name: "Party",
    group: "Karaoke",
    hint: "Fun, slight slap-back",
    params: {
      wet: 0.6,
      lowCut: 120,
      eqLow: 2,
      eqHigh: 3,
      drive: 0.12,
      reverbMix: 0.5,
      reverbSize: 0.45,
      reverbDecay: 0.5,
      reverbDamp: 0.35,
      delayMix: 0.18,
      delayTime: 0.14,
      delayFeedback: 0.2,
      delayDamp: 0.45,
    },
  },

  // ── Singing ─────────────────────────────────────────────────────────────
  {
    id: "vocal-booth",
    name: "Vocal Booth",
    group: "Singing",
    hint: "Tiny, intimate, dry",
    params: {
      wet: 0.3,
      lowCut: 100,
      eqMid: 1,
      eqMidFreq: 3000,
      reverbMix: 0.22,
      reverbSize: 0.1,
      reverbDecay: 0.2,
      reverbDamp: 0.55,
    },
  },
  {
    id: "studio-plate",
    name: "Studio Plate",
    group: "Singing",
    hint: "Classic polished plate",
    params: {
      wet: 0.45,
      lowCut: 100,
      eqHigh: 2,
      reverbMix: 0.4,
      reverbSize: 0.3,
      reverbDecay: 0.6,
      reverbDamp: 0.25,
    },
  },
  {
    id: "pop-sheen",
    name: "Pop Sheen",
    group: "Singing",
    hint: "Plate, gentle slap and shimmer",
    params: {
      wet: 0.5,
      lowCut: 115,
      eqLow: -1,
      eqHigh: 3.5,
      drive: 0.05,
      reverbMix: 0.42,
      reverbSize: 0.32,
      reverbDecay: 0.55,
      reverbDamp: 0.25,
      delayMix: 0.14,
      delayTime: 0.09,
      delayFeedback: 0.14,
      delayDamp: 0.4,
      chorusMix: 0.22,
      chorusRate: 1.1,
      chorusDepth: 0.28,
    },
  },
  {
    id: "rnb-silk",
    name: "R&B Silk",
    group: "Singing",
    hint: "Smooth eighth-note echo",
    params: {
      wet: 0.5,
      lowCut: 105,
      eqLow: 1.5,
      eqMid: -1,
      eqMidFreq: 900,
      eqHigh: 2,
      reverbMix: 0.35,
      reverbSize: 0.35,
      reverbDecay: 0.55,
      reverbDamp: 0.45,
      delayMix: 0.22,
      delayTime: 0.25,
      delayFeedback: 0.24,
      delayDamp: 0.6,
      chorusMix: 0.15,
      chorusRate: 0.5,
      chorusDepth: 0.25,
    },
  },
  {
    id: "ballad-hall",
    name: "Ballad Hall",
    group: "Singing",
    hint: "Long lush tail",
    params: {
      wet: 0.6,
      lowCut: 95,
      eqHigh: 1.5,
      reverbMix: 0.68,
      reverbSize: 0.7,
      reverbDecay: 0.72,
      reverbDamp: 0.35,
      delayMix: 0.08,
      delayTime: 0.3,
      delayFeedback: 0.15,
      delayDamp: 0.55,
    },
  },
  {
    id: "gospel-choir",
    name: "Gospel Choir",
    group: "Singing",
    hint: "Huge church space",
    params: {
      wet: 0.7,
      lowCut: 90,
      eqLow: 1,
      eqHigh: 2,
      reverbMix: 0.85,
      reverbSize: 0.9,
      reverbDecay: 0.8,
      reverbDamp: 0.3,
      delayMix: 0.1,
      delayTime: 0.28,
      delayFeedback: 0.18,
      delayDamp: 0.5,
      chorusMix: 0.2,
      chorusRate: 0.4,
      chorusDepth: 0.35,
    },
  },
  {
    id: "rock-grit",
    name: "Rock Grit",
    group: "Singing",
    hint: "Driven, medium room",
    params: {
      wet: 0.5,
      lowCut: 140,
      eqLow: -2,
      eqMid: 3,
      eqMidFreq: 2200,
      eqHigh: 1,
      drive: 0.45,
      reverbMix: 0.35,
      reverbSize: 0.3,
      reverbDecay: 0.45,
      reverbDamp: 0.45,
      delayMix: 0.12,
      delayTime: 0.12,
      delayFeedback: 0.2,
      delayDamp: 0.5,
    },
  },

  // ── Mehfil ──────────────────────────────────────────────────────────────
  {
    id: "mehfil-light",
    name: "Mehfil Light",
    group: "Mehfil",
    hint: "Small gathering, soft echo",
    params: {
      wet: 0.5,
      lowCut: 100,
      eqLow: 1,
      eqHigh: 1.5,
      reverbMix: 0.4,
      reverbSize: 0.4,
      reverbDecay: 0.5,
      reverbDamp: 0.45,
      delayMix: 0.18,
      delayTime: 0.2,
      delayFeedback: 0.18,
      delayDamp: 0.5,
    },
  },
  {
    id: "mehfil-classic",
    name: "Mehfil Classic",
    group: "Mehfil",
    hint: "Warm hall echo",
    params: {
      wet: 0.6,
      lowCut: 95,
      eqLow: 1.5,
      eqHigh: 1.5,
      reverbMix: 0.55,
      reverbSize: 0.55,
      reverbDecay: 0.6,
      reverbDamp: 0.45,
      delayMix: 0.3,
      delayTime: 0.26,
      delayFeedback: 0.3,
      delayDamp: 0.55,
    },
  },
  {
    id: "mehfil-grand",
    name: "Mehfil Grand",
    group: "Mehfil",
    hint: "Big hall, long repeats",
    params: {
      wet: 0.7,
      lowCut: 90,
      eqLow: 1.5,
      eqHigh: 2,
      reverbMix: 0.72,
      reverbSize: 0.75,
      reverbDecay: 0.72,
      reverbDamp: 0.4,
      delayMix: 0.4,
      delayTime: 0.34,
      delayFeedback: 0.4,
      delayDamp: 0.55,
    },
  },

  // ── Qawwali ─────────────────────────────────────────────────────────────
  {
    id: "qawwali",
    name: "Qawwali",
    group: "Qawwali",
    hint: "Powerful, rhythmic echo",
    params: {
      wet: 0.72,
      lowCut: 100,
      eqLow: 1,
      eqMid: 2,
      eqMidFreq: 2400,
      eqHigh: 1.5,
      drive: 0.12,
      reverbMix: 0.6,
      reverbSize: 0.6,
      reverbDecay: 0.65,
      reverbDamp: 0.4,
      delayMix: 0.45,
      delayTime: 0.3,
      delayFeedback: 0.45,
      delayDamp: 0.5,
    },
  },

  // ── Tillawat ────────────────────────────────────────────────────────────
  {
    id: "tillawat-soft",
    name: "Tillawat Soft",
    group: "Tillawat",
    hint: "Clean, subtle space",
    params: {
      wet: 0.45,
      lowCut: 90,
      eqHigh: 1,
      reverbMix: 0.42,
      reverbSize: 0.5,
      reverbDecay: 0.55,
      reverbDamp: 0.5,
      delayMix: 0.12,
      delayTime: 0.28,
      delayFeedback: 0.14,
      delayDamp: 0.6,
    },
  },
  {
    id: "tillawat-masjid",
    name: "Tillawat Masjid",
    group: "Tillawat",
    hint: "Masjid-style echo",
    params: {
      wet: 0.65,
      lowCut: 85,
      eqLow: 1,
      eqHigh: 1.5,
      reverbMix: 0.7,
      reverbSize: 0.75,
      reverbDecay: 0.7,
      reverbDamp: 0.45,
      delayMix: 0.3,
      delayTime: 0.38,
      delayFeedback: 0.3,
      delayDamp: 0.6,
    },
  },
  {
    id: "tillawat-grand",
    name: "Tillawat Grand",
    group: "Tillawat",
    hint: "Large dome, long tail",
    params: {
      wet: 0.78,
      lowCut: 80,
      eqLow: 1.5,
      eqHigh: 1.5,
      reverbMix: 0.88,
      reverbSize: 0.95,
      reverbDecay: 0.85,
      reverbDamp: 0.4,
      delayMix: 0.4,
      delayTime: 0.46,
      delayFeedback: 0.42,
      delayDamp: 0.6,
    },
  },

  // ── Naat ────────────────────────────────────────────────────────────────
  {
    id: "naat",
    name: "Naat",
    group: "Naat",
    hint: "Melodic, warm repeats",
    params: {
      wet: 0.62,
      lowCut: 90,
      eqLow: 2,
      eqHigh: 1.5,
      reverbMix: 0.6,
      reverbSize: 0.6,
      reverbDecay: 0.65,
      reverbDamp: 0.45,
      delayMix: 0.32,
      delayTime: 0.34,
      delayFeedback: 0.32,
      delayDamp: 0.6,
      chorusMix: 0.12,
      chorusRate: 0.45,
      chorusDepth: 0.25,
    },
  },

  // ── FX ──────────────────────────────────────────────────────────────────
  {
    id: "stadium",
    name: "Stadium",
    group: "FX",
    hint: "Massive slap-back",
    params: {
      wet: 0.8,
      lowCut: 90,
      eqHigh: 2,
      reverbMix: 0.85,
      reverbSize: 0.95,
      reverbDecay: 0.8,
      reverbDamp: 0.35,
      delayMix: 0.5,
      delayTime: 0.35,
      delayFeedback: 0.5,
      delayDamp: 0.5,
    },
  },
  {
    id: "robot",
    name: "Robot",
    group: "FX",
    hint: "Metallic comb tone",
    params: {
      wet: 0.8,
      lowCut: 150,
      eqMid: 4,
      eqMidFreq: 1500,
      drive: 0.55,
      reverbMix: 0.1,
      reverbSize: 0.1,
      reverbDecay: 0.3,
      reverbDamp: 0.5,
      delayMix: 0.9,
      delayTime: 0.02,
      delayFeedback: 0.7,
      delayDamp: 0.2,
    },
  },
  {
    id: "megaphone",
    name: "Megaphone",
    group: "FX",
    hint: "Thin and distorted",
    params: {
      wet: 0.6,
      lowCut: 350,
      eqLow: -8,
      eqMid: 6,
      eqMidFreq: 2000,
      eqHigh: -6,
      drive: 0.7,
      reverbMix: 0.05,
      reverbSize: 0.1,
      reverbDecay: 0.2,
      reverbDamp: 0.7,
    },
  },
  {
    id: "cave",
    name: "Cave",
    group: "FX",
    hint: "Dark endless space",
    params: {
      wet: 0.85,
      lowCut: 70,
      eqHigh: -4,
      reverbMix: 0.95,
      reverbSize: 1,
      reverbDecay: 0.9,
      reverbDamp: 0.75,
      delayMix: 0.6,
      delayTime: 0.5,
      delayFeedback: 0.65,
      delayDamp: 0.8,
    },
  },
];

export const DEFAULT_PRESET_ID = "clean";

export function findPreset(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}

/**
 * Resolves a preset to a full parameter set. Levels are carried over from the
 * current state because input/output gain are mic-and-room controls, not part
 * of the sound design.
 */
export function resolvePreset(
  preset: Preset,
  levels: Pick<EffectParams, "inputGain" | "outputGain">,
): EffectParams {
  return {
    ...DRY_PARAMS,
    ...preset.params,
    inputGain: levels.inputGain,
    outputGain: levels.outputGain,
  };
}
